#web_controller:
#    resource: ../../src/Controller/
#    type: annotation
#
#rest_controller:
#    resource: ../../src/Api/Controller/Rest/
#    type: annotation
#    prefix: /api

controllers:
    resource: ../../src/Controller/
    type: annotation
